In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_excel("../data/Pizza_Sales_Dataset.xlsx")

In [3]:
df.head()

,Date,Pizza_Name,Category,Pizza_Code,Price_USD,Sales,Unsold,Revenue,Rating
0,01 January 2022,Deluxe,Non-Veg,4,15,61,7,915,Average Seller
1,01 January 2022,Double Cheese,Veg,5,9,68,9,612,Average Seller
2,01 January 2022,Farmhouse,Veg,3,7,284,23,1988,Top Seller
3,02 January 2023,Deluxe,Non-Veg,4,15,133,9,1995,Top Seller
4,02 January 2023,Double Cheese,Veg,5,9,194,21,1746,Top Seller

In [7]:
#Data Features 
df["Date"] = pd.to_datetime(df["Date"])
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Month_Name"] = df["Date"].dt.month_name()
df["Day"] = df["Date"].dt.day
df["Day_Name"] = df["Date"].dt.day_name()

In [8]:
df.head()

,Date,Pizza_Name,Category,Pizza_Code,Price_USD,Sales,Unsold,Revenue,Rating,Year,Month,Month_Name,Day,Day_Name
0,2022-01-01,Deluxe,Non-Veg,4,15,61,7,915,Average Seller,2022,1,January,1,Saturday
1,2022-01-01,Double Cheese,Veg,5,9,68,9,612,Average Seller,2022,1,January,1,Saturday
2,2022-01-01,Farmhouse,Veg,3,7,284,23,1988,Top Seller,2022,1,January,1,Saturday
3,2023-01-02,Deluxe,Non-Veg,4,15,133,9,1995,Top Seller,2023,1,January,2,Monday
4,2023-01-02,Double Cheese,Veg,5,9,194,21,1746,Top Seller,2023,1,January,2,Monday

In [9]:
#Revenue Per Pizza
df["Revenue_Per_Pizza"] = df["Revenue"]/df["Sales"]

In [11]:
df[["Sales" , "Revenue" , "Revenue_Per_Pizza"]].head()

   Sales  Revenue  Revenue_Per_Pizza
0     61      915               15.0
1     68      612                9.0
2    284     1988                7.0
3    133     1995               15.0
4    194     1746                9.0

In [14]:
#Unsold Rates
df["Unsold_Rate"] = (df["Unsold"] / (df["Sales"] + df["Unsold"]) )*100

In [18]:
df[["Sales" ,"Unsold" , "Unsold_Rate"]].head()

   Sales  Unsold  Unsold_Rate
0     61       7    10.294118
1     68       9    11.688312
2    284      23     7.491857
3    133       9     6.338028
4    194      21     9.767442

In [29]:
#Total Production

df["Total_Production"] = df["Unsold"] + df["Sales"]

In [30]:
df[["Sales" , "Unsold" , "Total_Production"]].head()

   Sales  Unsold  Total_Production
0     61       7                68
1     68       9                77
2    284      23               307
3    133       9               142
4    194      21               215

In [37]:
#Sales Rate
df["Sales_Rate"] = (
    df["Sales"] / df["Total_Production"] * 100 )

In [38]:
df[["Sales" , "Unsold" , "Total_Production" , "Sales_Rate"]].head()

   Sales  Unsold  Total_Production  Sales_Rate
0     61       7                68   89.705882
1     68       9                77   88.311688
2    284      23               307   92.508143
3    133       9               142   93.661972
4    194      21               215   90.232558

In [39]:
#Pizza Performance Category
df["Sales"].describe

<bound method NDFrame.describe of 0      61
1      68
2     284
3     133
4     194
     ...
56    282
57    231
58    150
59    176
60    240
Name: Sales, Length: 61, dtype: int64>

In [40]:
df["Sales_Performance"] = pd.qcut(df["Sales"], q = 3, labels = ["Low" , "Medium" , "High"])

In [41]:
df["Pizza_Sales" , "

SyntaxError: unterminated string literal (detected at line 1) (884975738.py, line 1)

In [ ]:
S